In [1]:
import numpy as np

# Stock 1 price data (5 days × 3 features: Open, High, Low)
stock1 = np.array([
    [100, 105, 98],
    [102, 108, 101],
    [104, 110, 103],
    [103, 109, 102],
    [105, 111, 104]
])

# Stock 2 price data
stock2 = np.array([
    [98, 104, 97],
    [101, 107, 100],
    [103, 109, 102],
    [102, 108, 101],
    [104, 110, 103]
])

print("Stock 1 Matrix:\n", stock1)
print("\nStock 2 Matrix:\n", stock2)

# Element-wise sum
sum_matrix = stock1 + stock2
print("\nElement-wise Sum of matrices:\n", sum_matrix)

# Element-wise difference
difference_matrix = stock1 - stock2
print("\nElement-wise Difference of matrices:\n", difference_matrix)

Stock 1 Matrix:
 [[100 105  98]
 [102 108 101]
 [104 110 103]
 [103 109 102]
 [105 111 104]]

Stock 2 Matrix:
 [[ 98 104  97]
 [101 107 100]
 [103 109 102]
 [102 108 101]
 [104 110 103]]

Element-wise Sum of matrices:
 [[198 209 195]
 [203 215 201]
 [207 219 205]
 [205 217 203]
 [209 221 207]]

Element-wise Difference of matrices:
 [[2 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
